### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by golyalpha** [jyeary/openshift-craftbukkit-quickstart#2]
I followed your instructions step by step, but it seems that craftbukkit isn't running.

**Comment by golyalpha** [comment]
Ok, so i screwed with it for a loong time, and still nothing, and as a bonus i can't ssh to my workspace for some reason. And yes, i added my public key.

**Comment by golyalpha** [comment]
ok, so this is my output:
C:\Users\ ****_>rhc ssh jbossas
DL is deprecated, please use Fiddle
Connecting to 5401ca8b500446830a000977@jbossas-developer0586.rhcloud.com ...
Enter passphrase for key '/cygdrive/c/Users/**_**/.ssh/id_rsa':
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

I get simmilar output on craftbukkit, but the key output is the same.

**Comment by ExplosiveCraft** [comment]
I updated it :)
https://github.com/ExplosiveCraft
